# Generated by Django 5.2.13 on 2026-05-15 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('approved', '承認済み'), ('rejected', '却下'), ('cancelled', 'キャンセル')], default='pending', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('expected_start_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='assets.asset')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan request',
                'verbose_name_plural': 'Loan requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_start_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_record', to='loans.loanrequest')),
            ],
            options={
                'verbose_name': 'Loan record',
                'verbose_name_plural': 'Loan records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField()),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_record', to='loans.loanrecord')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return record',
                'verbose_name_plural': 'Return records',
                'ordering': ['-returned_at'],
            },
        ),
    ]
