# Generated by Django 5.2.13 on 2026-05-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
