# Generated by Django 5.2.13 on 2026-05-16 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('loan_requested', '貸出申請'), ('loan_approved', '貸出承認'), ('loan_rejected', '貸出却下'), ('return_requested', '返却申請'), ('return_confirmed', '返却確認'), ('incident_reported', 'インシデント報告'), ('incident_resolved', 'インシデント解決'), ('inventory_recorded', '棚卸し結果記録'), ('inventory_closed', '棚卸し完了')], max_length=50)),
                ('asset_code', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
